version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directories:
      - "/"
      - "/examples"
      - "/crates/tosca-esp32c3/examples/light"
      - "/crates/tosca-esp32c3/examples/light-with-state"
      - "/crates/tosca-esp32c3/examples/light-with-events"
    schedule:
      interval: "daily"
