[package]
name = "tosca-esp32c3"
version = "0.2.0"
edition = "2024"
authors = ["Michele Valsesia <michele.valsesia@toscalabs.org>"]
description = "A library for building Tosca firmware that runs on ESP32-C3 boards."
keywords = ["iot", "iot-library", "firmware", "device", "esp32-c3"]
documentation = "https://docs.rs/tosca-esp32c3"
readme = "README.md"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/ToscaLabs/tosca/tree/master/crates/tosca-esp32c3"
rust-version = "1.96"

[package.metadata.docs.rs]
default-target = "riscv32imc-unknown-none-elf"
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
# Tosca workspace crate
tosca = { path = "../tosca", version = "0.2.0", default-features = false }

# Multithread critical section
critical-section = "1.2.0"

# HTTP server
edge-http = { version = "0.8.0", features = ["io"] }

# mDNS service
edge-mdns = { version = "0.8.0", default-features = false, features = ["io"] }

# Networking traits
edge-nal = "0.7.0"
edge-nal-embassy = "0.9.0"

# Embassy framework
embassy-executor = { version = "0.10.0", default-features = false, features = ["log"] }
embassy-net = { version = "0.9.1", default-features = false, features = ["dhcpv4", "dns", "log", "medium-ethernet", "tcp", "udp"] }
embassy-sync = { version = "0.8.0", default-features = false }
embassy-time = { version = "0.5.1", default-features = false, features = ["log"] }

# Async IO traits
embedded-io-async = "0.7.0"

# ESP dependencies
esp-alloc = "0.11.0"
esp-hal = { version = "~1.2.2", features = ["esp32c3", "log-04", "unstable"] }
esp-rtos = { version = "0.4.0", features = ["embassy", "esp-alloc", "esp-radio", "esp32c3", "log-04"] }
esp-println = { version = "0.18.0", features = ["esp32c3", "log-04"] }
esp-radio = { version = "1.0.0-beta.1", features = ["esp-alloc", "esp32c3", "log-04", "wifi"] }

# Logging
log = "0.4.33"

# Random traits
rand_core = "0.10.1"

# MQTT protocol
rust-mqtt = { version = "0.5.1", default-features = false, features = ["v5", "alloc"] }

# Serialization
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = { version = "1", default-features = false, features = ["alloc"] }

[lints.rust]
rust_2018_idioms = { level = "deny", priority = -1 }
missing_docs = "deny"
warnings = "deny"
unused_results = "deny"

[lints.clippy]

[lints.rustdoc]
broken_intra_doc_links = "deny"
invalid_html_tags = "deny"
