name: esp

on:
  push:
    branches: [master]
    paths:
      - 'crates/tosca/**/Cargo.lock'
      - 'crates/tosca/**/*.rs'
      - 'crates/tosca/**/*.toml'

      - 'crates/tosca-esp32c3/**/Cargo.lock'
      - 'crates/tosca-esp32c3/**/*.rs'
      - 'crates/tosca-esp32c3/**/*.sh'
      - 'crates/tosca-esp32c3/**/*.yml'
      - 'crates/tosca-esp32c3/**/*.toml'
    tags:
      - 'v*.*.*' # Run when a new version is being published
  pull_request:
    branches: [master]
    types: [opened, synchronize]
    paths:
      - 'crates/tosca/**/Cargo.lock'
      - 'crates/tosca/**/*.rs'
      - 'crates/tosca/**/*.toml'

      - 'crates/tosca-esp32c3/**/Cargo.lock'
      - 'crates/tosca-esp32c3/**/*.rs'
      - 'crates/tosca-esp32c3/**/*.sh'
      - 'crates/tosca-esp32c3/**/*.yml'
      - 'crates/tosca-esp32c3/**/*.toml'

jobs:
  rustfmt-clippy-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install ldproxy
        run: |
          cargo install ldproxy

      - name: Build tosca-esp32c3
        shell: bash
        run: |
          set -e

          cd crates/tosca-esp32c3

          cargo fmt --all -- --check --verbose
          cargo clippy -- -Dclippy::all -Dclippy::pedantic

          RUSTDOCFLAGS="-D warnings" cargo doc --no-deps

          cargo build

      - name: Build all examples
        run: |
          set -e
          for ex in crates/tosca-esp32c3/examples/*; do
            if [ -d "$ex" ] && [ -f "$ex/Cargo.toml" ]; then
              name=$(basename "$ex")

              echo "=============================="
              echo "CI: $name"
              echo "=============================="

              (
                cd "$ex"

                cargo fmt --all -- --check --verbose
                cp cfg.toml.example cfg.toml
                cargo clippy -- -Dclippy::all -Dclippy::pedantic
                cargo build
              )
            fi
          done
